# Generated by Django 2.0.1 on 2018-01-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('books', '0001_initial'), ('books', '0002_auto_20180120_1950'), ('books', '0003_auto_20180120_1953')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
